version: "3"
services:
  api:
    build: burakblm/python-full-stack-backend:latest
    ports:
      - 8000:8000
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - ALGORITHM=${ALGORITHM}
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data

  prestart:
    image: burakblm/python-full-stack-backend:latest
    command: bash /app/scripts/prestart.sh
    environment:
      - PYTHONPATH=/app
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - ALGORITHM=${ALGORITHM}
    depends_on:
      - postgres
      - api

volumes:
  postgres-db:
